version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft_server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "VANILLA"
      MEMORY: "2G"
      DIFFICULTY: "normal"
      MODE: "survival"
      MOTD: "Welcome to My Minecraft Server"
      PVP: "true"
      SPAWN_PROTECTION: "0"
      ENFORCE_WHITELIST: "false"
    volumes:
      - ./minecraft-data:/data
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  minecraft-data: